modLoader="kotlinforforge"
loaderVersion="[5.12,)"
license="MMPL-1.0.1"
issueTrackerURL="https://github.com/The-Mystora-Project/WoodenAccentsMod/issues"

[[mods]]
modId="wooden_accents_mod"
version="${version}"
displayName="Wooden Accents Mod"
authors="Mystery2099"
description='''Vanilla-scale furniture and structural accents for every wood type.'''
logoFile="assets/wooden_accents_mod/icon.png"

[[dependencies.wooden_accents_mod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.wooden_accents_mod]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.wooden_accents_mod]]
modId="kotlinforforge"
type="required"
versionRange="[5.12,)"
ordering="NONE"
side="BOTH"

[[dependencies.wooden_accents_mod]]
modId="voxlib"
type="required"
versionRange="[1.8.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.wooden_accents_mod]]
modId="shulkerboxtooltip"
type="optional"
versionRange="[5.1.9,)"
ordering="NONE"
side="CLIENT"
